Task30: Introduction to Selenium WebDriver
VarvaraKrestyanova/java-aqa-selenium pull request #3
Opened 2022-03-28 19:52 UTC by VarvaraKrestyanova

credentials.properties is not pushed. let me know, please, if you need for review

2022-03-29 05:29 UTC, EugenBorisik requested changes
1. Please add separate class with all 8 types of By (they can be on different pages, the goal is to see all of them, there are no needs to use them in the test)
2. Optional (out of task's scope): I see that you have already used page object pattern. According to this pattern each public method must return any value/current page/new page, but not void.
3. Optional (out of task's scope): The best practice is to set implicit waiter once after WebDriver instance initialization and do not change it in runtime. Set it in @BeforeEach method in your case.

2022-03-29 05:29 UTC, EugenBorisik commented on UnitTesting-master/pom.xml
> +        </dependency>
My recommendation is to use one artifactId "selenium-java", it contains all necessary dependencies

2022-03-31 11:21 UTC, VarvaraKrestyanova commented
@EugenBorisik please, review

2022-03-31 12:34 UTC, EugenBorisik approved these changes

2022-03-31 12:34 UTC, EugenBorisik commented on UnitTesting-master/src/test/java/seleniumMail/Helpers/ByLocators.java
> +public class ByLocators {
+ By.name, By.partialLinkText

2022-04-01 11:29 UTC, merged